# docker-compose.yaml
services:
  headless:
    build:
      context: .
      dockerfile: Dockerfile.headless
    stdin_open: true                # Keep stdin open even if not attached
    tty: true                       # Allocate a pseudo-TTY
    image: sebdufond/headless-rally
    ports:
      - 5000:5000
      - 7654:7654
